### ISSUE TITLE
there is no install.R

### ISSUE THREAD

**Issue by cailiangliang765** [Bioconductor/AnVIL_Docker#4]
Hi, I could not find the insatll.R file as is in "Within the file install.R in rstudio/bioc3.8 or rstudio/bioc3.9, ". can you tell me where is it ?

**Comment by mtmorgan** [comment]
@nturaga this refers to https://github.com/Bioconductor/AnVIL_Docker/blame/master/rstudio/README.md#L5

**Comment by cailiangliang765** [comment]
> @nturaga this refers to https://github.com/Bioconductor/AnVIL_Docker/blame/master/rstudio/README.md#L5

@mtmorgan Many thanks for your reply.

**Comment by nturaga** [comment]
Yes. I think this line in the README.md should be removed. Thanks @mtmorgan
